name = "kura-auth"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
SITE_ORIGIN = "https://kura.monster"
REDIRECT_URI = "https://kura-auth.kuras.workers.dev/auth/callback"

[assets]
directory = "./public"
binding = "ASSETS"
